version: "3"

services:
  python:
    container_name: webapp
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-python
    ports:
      - "5000:5000"

  redis:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"

  db:
    container_name: postgres-server
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dbadmin
      POSTGRES_USER: dbpass
      POSTGRES_DB: bank_app
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
